name: Deploy to Tomcat

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Deploy to Tomcat
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.TOMCAT_HOST }}
          username: ${{ secrets.TOMCAT_USERNAME }}
          password: ${{ secrets.TOMCAT_PASSWORD }}
          port: 22
          source: "target/Web-experiences-1.0-SNAPSHOT.war"
          target: "/path/to/tomcat/webapps/"